project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

      - text: "slides"
        menu:
         - text: "first slide"
           href: slides/slides.ipynb
           
           
format:
  html:
    theme: cosmo
    toc: true



